export type ComponentCategory =
  | 'text'
  | 'animations'
  | 'components'
  | 'backgrounds'
  | 'blocks';

export interface ComponentEntry {
  name: string;
  slug: string;
  category: ComponentCategory;
  description: string;
  sourceRef: string;
  featured: boolean;
}

export const CATEGORY_LABELS: Record<ComponentCategory, string> = {
  text: 'Text',
  animations: 'Animations',
  components: 'Components',
  backgrounds: 'Backgrounds',
  blocks: 'Blocks',
};

export const componentRegistry: ComponentEntry[] = [
  // Text Animations
  {
    name: 'Split Text',
    slug: 'split-text',
    category: 'text',
    description: 'Text that splits apart and animates character by character',
    sourceRef: 'reactbits.dev/text-animations/split-text',
    featured: false,
  },
  {
    name: 'Blur Text',
    slug: 'blur-text',
    category: 'text',
    description: 'Text that fades in with a blur effect',
    sourceRef: 'reactbits.dev/text-animations/blur-text',
    featured: true,
  },
  {
    name: 'Circular Text',
    slug: 'circular-text',
    category: 'text',
    description: 'Text arranged in a circular path with rotation',
    sourceRef: 'reactbits.dev/text-animations/circular-text',
    featured: false,
  },
  {
    name: 'Text Type',
    slug: 'text-type',
    category: 'text',
    description: 'Typewriter effect that types text character by character',
    sourceRef: 'reactbits.dev/text-animations/text-type',
    featured: false,
  },
  {
    name: 'Shuffle',
    slug: 'shuffle',
    category: 'text',
    description:
      'Text that shuffles through random characters before revealing',
    sourceRef: 'reactbits.dev/text-animations/shuffle',
    featured: false,
  },
  {
    name: 'Shiny Text',
    slug: 'shiny-text',
    category: 'text',
    description: 'Text with a shimmering light sweep effect',
    sourceRef: 'reactbits.dev/text-animations/shiny-text',
    featured: false,
  },
  {
    name: 'Text Pressure',
    slug: 'text-pressure',
    category: 'text',
    description: 'Text that reacts to cursor pressure and proximity',
    sourceRef: 'reactbits.dev/text-animations/text-pressure',
    featured: false,
  },
  {
    name: 'Curved Loop',
    slug: 'curved-loop',
    category: 'text',
    description: 'Text flowing along a curved looping path',
    sourceRef: 'reactbits.dev/text-animations/curved-loop',
    featured: false,
  },
  {
    name: 'Falling Text',
    slug: 'falling-text',
    category: 'text',
    description: 'Characters that fall and stack with physics',
    sourceRef: 'reactbits.dev/text-animations/falling-text',
    featured: false,
  },
  {
    name: 'Decrypted Text',
    slug: 'decrypted-text',
    category: 'text',
    description: 'Text that decrypts from scrambled characters',
    sourceRef: 'reactbits.dev/text-animations/decrypted-text',
    featured: false,
  },
  {
    name: 'True Focus',
    slug: 'true-focus',
    category: 'text',
    description: 'Only the focused word is sharp, rest is blurred',
    sourceRef: 'reactbits.dev/text-animations/true-focus',
    featured: false,
  },
  {
    name: 'Scroll Float',
    slug: 'scroll-float',
    category: 'text',
    description: 'Text that floats upward as you scroll',
    sourceRef: 'reactbits.dev/text-animations/scroll-float',
    featured: false,
  },
  {
    name: 'Scroll Reveal',
    slug: 'scroll-reveal',
    category: 'text',
    description: 'Text revealed progressively on scroll',
    sourceRef: 'reactbits.dev/text-animations/scroll-reveal',
    featured: false,
  },
  {
    name: 'ASCII Text',
    slug: 'ascii-text',
    category: 'text',
    description: 'Text rendered in ASCII art style',
    sourceRef: 'reactbits.dev/text-animations/ascii-text',
    featured: false,
  },
  {
    name: 'Scrambled Text',
    slug: 'scrambled-text',
    category: 'text',
    description: 'Text that scrambles and unscrambles on hover',
    sourceRef: 'reactbits.dev/text-animations/scrambled-text',
    featured: false,
  },
  {
    name: 'Rotating Text',
    slug: 'rotating-text',
    category: 'text',
    description: 'Text that rotates through multiple words',
    sourceRef: 'reactbits.dev/text-animations/rotating-text',
    featured: false,
  },
  {
    name: 'Glitch Text',
    slug: 'glitch-text',
    category: 'text',
    description: 'Text with a digital glitch distortion effect',
    sourceRef: 'reactbits.dev/text-animations/glitch-text',
    featured: true,
  },
  {
    name: 'Variable Proximity',
    slug: 'variable-proximity',
    category: 'text',
    description: 'Font weight changes based on cursor distance',
    sourceRef: 'reactbits.dev/text-animations/variable-proximity',
    featured: false,
  },
  {
    name: 'Scroll Velocity',
    slug: 'scroll-velocity',
    category: 'text',
    description: 'Marquee text that speeds up with scroll velocity',
    sourceRef: 'reactbits.dev/text-animations/scroll-velocity',
    featured: false,
  },
  {
    name: 'Letter Swap',
    slug: 'letter-swap',
    category: 'text',
    description: 'Letters swap positions with smooth animation on hover',
    sourceRef: 'fancycomponents.dev',
    featured: false,
  },

  // Animations
  {
    name: 'Electric Border',
    slug: 'electric-border',
    category: 'animations',
    description: 'An electric current effect that travels along a border',
    sourceRef: 'reactbits.dev/animations/electric-border',
    featured: true,
  },
  {
    name: 'Glare Hover',
    slug: 'glare-hover',
    category: 'animations',
    description: 'A glare light effect that follows cursor on hover',
    sourceRef: 'reactbits.dev/animations/glare-hover',
    featured: false,
  },
  {
    name: 'Antigravity',
    slug: 'antigravity',
    category: 'animations',
    description: 'Elements that float upward defying gravity',
    sourceRef: 'reactbits.dev/animations/antigravity',
    featured: false,
  },
  {
    name: 'Logo Loop',
    slug: 'logo-loop',
    category: 'animations',
    description: 'Continuous looping logo animation',
    sourceRef: 'reactbits.dev/animations/logo-loop',
    featured: false,
  },
  {
    name: 'Target Cursor',
    slug: 'target-cursor',
    category: 'animations',
    description: 'A crosshair target that follows the cursor',
    sourceRef: 'reactbits.dev/animations/target-cursor',
    featured: false,
  },
  {
    name: 'Magic Rings',
    slug: 'magic-rings',
    category: 'animations',
    description: 'Concentric rings with magical animation effects',
    sourceRef: 'reactbits.dev/animations/magic-rings',
    featured: false,
  },
  {
    name: 'Magnet',
    slug: 'magnet',
    category: 'animations',
    description: 'Element that attracts toward the cursor like a magnet',
    sourceRef: 'reactbits.dev/animations/magnet',
    featured: false,
  },
  {
    name: 'Pixel Trail',
    slug: 'pixel-trail',
    category: 'animations',
    description: 'Pixelated trail effect that follows cursor movement',
    sourceRef: 'reactbits.dev/animations/pixel-trail',
    featured: false,
  },
  {
    name: 'Metallic Paint',
    slug: 'metallic-paint',
    category: 'animations',
    description: 'A metallic paint shader effect on surfaces',
    sourceRef: 'reactbits.dev/animations/metallic-paint',
    featured: false,
  },
  {
    name: 'Shape Blur',
    slug: 'shape-blur',
    category: 'animations',
    description: 'Shapes that blur and morph dynamically',
    sourceRef: 'reactbits.dev/animations/shape-blur',
    featured: false,
  },
  {
    name: 'Crosshair',
    slug: 'crosshair',
    category: 'animations',
    description: 'Precision crosshair cursor effect',
    sourceRef: 'reactbits.dev/animations/crosshair',
    featured: false,
  },
  {
    name: 'Meta Balls',
    slug: 'meta-balls',
    category: 'animations',
    description: 'Organic metaball shapes that merge on proximity',
    sourceRef: 'reactbits.dev/animations/meta-balls',
    featured: false,
  },

  // Components
  {
    name: 'Animated List',
    slug: 'animated-list',
    category: 'components',
    description: 'List items that animate in with staggered timing',
    sourceRef: 'reactbits.dev/components/animated-list',
    featured: false,
  },
  {
    name: 'Scroll Stack',
    slug: 'scroll-stack',
    category: 'components',
    description: 'Cards that stack and scale as you scroll',
    sourceRef: 'reactbits.dev/components/scroll-stack',
    featured: false,
  },
  {
    name: 'Magic Bento',
    slug: 'magic-bento',
    category: 'components',
    description: 'Bento grid layout with interactive hover effects',
    sourceRef: 'reactbits.dev/components/magic-bento',
    featured: false,
  },
  {
    name: 'Circular Gallery',
    slug: 'circular-gallery',
    category: 'components',
    description: 'Image gallery arranged in a circular formation',
    sourceRef: 'reactbits.dev/components/circular-gallery',
    featured: false,
  },
  {
    name: 'Reflective Card',
    slug: 'reflective-card',
    category: 'components',
    description: 'Card with a realistic light reflection effect',
    sourceRef: 'reactbits.dev/components/reflective-card',
    featured: false,
  },
  {
    name: 'Fluid Glass',
    slug: 'fluid-glass',
    category: 'components',
    description: 'Glassmorphic surface with fluid motion',
    sourceRef: 'reactbits.dev/components/fluid-glass',
    featured: false,
  },
  {
    name: 'Tilted Card',
    slug: 'tilted-card',
    category: 'components',
    description: '3D card that tilts based on cursor position',
    sourceRef: 'reactbits.dev/components/tilted-card',
    featured: true,
  },
  {
    name: 'Glass Surface',
    slug: 'glass-surface',
    category: 'components',
    description: 'Frosted glass material surface effect',
    sourceRef: 'reactbits.dev/components/glass-surface',
    featured: false,
  },
  {
    name: 'Dome Gallery',
    slug: 'dome-gallery',
    category: 'components',
    description: 'Gallery with a dome-shaped 3D perspective',
    sourceRef: 'reactbits.dev/components/dome-gallery',
    featured: false,
  },
  {
    name: 'Folder',
    slug: 'folder',
    category: 'components',
    description: 'Interactive folder component that opens on click',
    sourceRef: 'reactbits.dev/components/folder',
    featured: false,
  },
  {
    name: 'Lanyard',
    slug: 'lanyard',
    category: 'components',
    description: 'ID badge on a lanyard with physics simulation',
    sourceRef: 'reactbits.dev/components/lanyard',
    featured: false,
  },
  {
    name: 'Dock',
    slug: 'dock',
    category: 'components',
    description: 'macOS-style dock with magnification on hover',
    sourceRef: 'reactbits.dev/components/dock',
    featured: false,
  },
  {
    name: 'Pixel Card',
    slug: 'pixel-card',
    category: 'components',
    description: 'Card with a pixelated reveal animation',
    sourceRef: 'reactbits.dev/components/pixel-card',
    featured: false,
  },
  {
    name: 'Border Glow',
    slug: 'border-glow',
    category: 'components',
    description: 'Card border that glows following the cursor',
    sourceRef: 'reactbits.dev/components/border-glow',
    featured: false,
  },
  {
    name: 'Flowing Menu',
    slug: 'flowing-menu',
    category: 'components',
    description: 'Navigation menu with flowing animation between items',
    sourceRef: 'reactbits.dev/components/flowing-menu',
    featured: false,
  },
  {
    name: 'Elastic Slider',
    slug: 'elastic-slider',
    category: 'components',
    description: 'Slider with elastic snap-back animation',
    sourceRef: 'reactbits.dev/components/elastic-slider',
    featured: false,
  },
  {
    name: 'Infinite Menu',
    slug: 'infinite-menu',
    category: 'components',
    description: 'Infinitely scrolling circular menu',
    sourceRef: 'reactbits.dev/components/infinite-menu',
    featured: false,
  },

  // Backgrounds
  {
    name: 'Line Waves',
    slug: 'line-waves',
    category: 'backgrounds',
    description: 'Animated wavy lines as a background effect',
    sourceRef: 'reactbits.dev/backgrounds/line-waves',
    featured: true,
  },
  {
    name: 'Soft Aurora',
    slug: 'soft-aurora',
    category: 'backgrounds',
    description: 'Gentle aurora borealis effect with flowing colors',
    sourceRef: 'reactbits.dev/backgrounds/soft-aurora',
    featured: true,
  },
  {
    name: 'Color Bends',
    slug: 'color-bends',
    category: 'backgrounds',
    description: 'Fluid color bending shader with customizable palette',
    sourceRef: 'reactbits.dev/backgrounds/color-bends',
    featured: true,
  },
  {
    name: 'Dark Veil',
    slug: 'dark-veil',
    category: 'backgrounds',
    description: 'Dark neural network pattern with hue shift and warp',
    sourceRef: 'reactbits.dev/backgrounds/dark-veil',
    featured: true,
  },
  {
    name: 'Light Pillar',
    slug: 'light-pillar',
    category: 'backgrounds',
    description: 'Raymarched glowing light pillar effect',
    sourceRef: 'reactbits.dev/backgrounds/light-pillar',
    featured: true,
  },
  {
    name: 'Evil Eye',
    slug: 'evil-eye',
    category: 'backgrounds',
    description: 'Procedural animated iris with pupil tracking',
    sourceRef: 'reactbits.dev/backgrounds/evil-eye',
    featured: true,
  },
  {
    name: 'Radar',
    slug: 'radar',
    category: 'backgrounds',
    description: 'Animated radar sweep with configurable rings',
    sourceRef: 'reactbits.dev/backgrounds/radar',
    featured: true,
  },

  // Blocks
  {
    name: 'Circling Elements',
    slug: 'circling-elements',
    category: 'blocks',
    description: 'Elements orbiting in a circle around a center point',
    sourceRef: 'fancycomponents.dev',
    featured: false,
  },
  {
    name: 'Marquee SVG Path',
    slug: 'marquee-svg-path',
    category: 'blocks',
    description: 'Content flowing along a custom SVG path',
    sourceRef: 'fancycomponents.dev',
    featured: false,
  },
  {
    name: 'Pixel Trail Block',
    slug: 'pixel-trail-block',
    category: 'blocks',
    description: 'Full-page pixel trail background with content overlay',
    sourceRef: 'fancycomponents.dev',
    featured: false,
  },
  {
    name: 'Parallax Floating',
    slug: 'parallax-floating',
    category: 'blocks',
    description: 'Images floating with parallax depth on mouse move',
    sourceRef: 'fancycomponents.dev',
    featured: false,
  },
  {
    name: 'MacBook Scroll',
    slug: 'macbook-scroll',
    category: 'blocks',
    description: 'MacBook opening animation driven by scroll',
    sourceRef: 'ui.aceternity.com/components',
    featured: true,
  },
  {
    name: 'Terminal',
    slug: 'terminal',
    category: 'blocks',
    description: 'Animated terminal window with typing effect',
    sourceRef: 'ui.aceternity.com/components/terminal',
    featured: false,
  },
  {
    name: 'World Map',
    slug: 'world-map',
    category: 'blocks',
    description: 'Interactive dotted world map with connections',
    sourceRef: 'ui.aceternity.com/components/world-map',
    featured: false,
  },
];

export function getComponentBySlug(slug: string): ComponentEntry | undefined {
  return componentRegistry.find(c => c.slug === slug);
}

export function getComponentsByCategory(
  category: ComponentCategory
): ComponentEntry[] {
  return componentRegistry.filter(c => c.category === category);
}

export function getFeaturedComponents(): ComponentEntry[] {
  return componentRegistry.filter(c => c.featured);
}
