// GENERATED BY scripts/generate-scope.mjs -- DO NOT EDIT BY HAND.
// Run `pnpm generate:scope` after adding or renaming a library component.

import Antigravity from '@/components/library/animations/Antigravity';
import Crosshair from '@/components/library/animations/Crosshair';
import ElectricBorder from '@/components/library/animations/ElectricBorder';
import GlareHover from '@/components/library/animations/GlareHover';
import LogoLoop from '@/components/library/animations/LogoLoop';
import MagicRings from '@/components/library/animations/MagicRings';
import Magnet from '@/components/library/animations/Magnet';
import MetaBalls from '@/components/library/animations/MetaBalls';
import MetallicPaint from '@/components/library/animations/MetallicPaint';
import PixelTrail from '@/components/library/animations/PixelTrail';
import ShapeBlur from '@/components/library/animations/ShapeBlur';
import TargetCursor from '@/components/library/animations/TargetCursor';
import ColorBends from '@/components/library/backgrounds/ColorBends';
import DarkVeil from '@/components/library/backgrounds/DarkVeil';
import EvilEye from '@/components/library/backgrounds/EvilEye';
import LightPillar from '@/components/library/backgrounds/LightPillar';
import LineWaves from '@/components/library/backgrounds/LineWaves';
import Radar from '@/components/library/backgrounds/Radar';
import SoftAurora from '@/components/library/backgrounds/SoftAurora';
import CirclingElements from '@/components/library/blocks/CirclingElements';
import MacbookScroll from '@/components/library/blocks/MacbookScroll';
import MarqueeAlongSvgPath from '@/components/library/blocks/MarqueeAlongSvgPath';
import ParallaxFloating, { FloatingElement } from '@/components/library/blocks/ParallaxFloating';
import Terminal from '@/components/library/blocks/Terminal';
import WorldMap from '@/components/library/blocks/WorldMap';
import AnimatedList from '@/components/library/components/AnimatedList';
import BorderGlow from '@/components/library/components/BorderGlow';
import CircularGallery from '@/components/library/components/CircularGallery';
import Dock from '@/components/library/components/Dock';
import DomeGallery from '@/components/library/components/DomeGallery';
import ElasticSlider from '@/components/library/components/ElasticSlider';
import FlowingMenu from '@/components/library/components/FlowingMenu';
import FluidGlass from '@/components/library/components/FluidGlass';
import Folder from '@/components/library/components/Folder';
import GlassSurface from '@/components/library/components/GlassSurface';
import InfiniteMenu from '@/components/library/components/InfiniteMenu';
import Lanyard from '@/components/library/components/Lanyard';
import LanyardImpl from '@/components/library/components/LanyardImpl';
import MagicBento from '@/components/library/components/MagicBento';
import PixelCard from '@/components/library/components/PixelCard';
import ReflectiveCard from '@/components/library/components/ReflectiveCard';
import ScrollStack, { ScrollStackItem } from '@/components/library/components/ScrollStack';
import TiltedCard from '@/components/library/components/TiltedCard';
import ASCIIText from '@/components/library/text-animations/ASCIIText';
import BlurText from '@/components/library/text-animations/BlurText';
import CircularText from '@/components/library/text-animations/CircularText';
import CurvedLoop from '@/components/library/text-animations/CurvedLoop';
import DecryptedText from '@/components/library/text-animations/DecryptedText';
import FallingText from '@/components/library/text-animations/FallingText';
import GlitchText from '@/components/library/text-animations/GlitchText';
import RotatingText from '@/components/library/text-animations/RotatingText';
import ScrambledText from '@/components/library/text-animations/ScrambledText';
import ScrollFloat from '@/components/library/text-animations/ScrollFloat';
import ScrollReveal from '@/components/library/text-animations/ScrollReveal';
import ScrollRevealCSS from '@/components/library/text-animations/ScrollRevealCSS';
import ScrollVelocity from '@/components/library/text-animations/ScrollVelocity';
import ShinyText from '@/components/library/text-animations/ShinyText';
import Shuffle from '@/components/library/text-animations/Shuffle';
import SplitText from '@/components/library/text-animations/SplitText';
import TextPressure from '@/components/library/text-animations/TextPressure';
import TextType from '@/components/library/text-animations/TextType';
import TrueFocus from '@/components/library/text-animations/TrueFocus';
import VariableProximity from '@/components/library/text-animations/VariableProximity';

/** Every library component, keyed by the name a blog post writes in its LiveStep code. */
export const liveScope: Record<string, unknown> = {
  ASCIIText,
  AnimatedList,
  Antigravity,
  BlurText,
  BorderGlow,
  CirclingElements,
  CircularGallery,
  CircularText,
  ColorBends,
  Crosshair,
  CurvedLoop,
  DarkVeil,
  DecryptedText,
  Dock,
  DomeGallery,
  ElasticSlider,
  ElectricBorder,
  EvilEye,
  FallingText,
  FloatingElement,
  FlowingMenu,
  FluidGlass,
  Folder,
  GlareHover,
  GlassSurface,
  GlitchText,
  InfiniteMenu,
  Lanyard,
  LanyardImpl,
  LightPillar,
  LineWaves,
  LogoLoop,
  MacbookScroll,
  MagicBento,
  MagicRings,
  Magnet,
  MarqueeAlongSvgPath,
  MetaBalls,
  MetallicPaint,
  ParallaxFloating,
  PixelCard,
  PixelTrail,
  Radar,
  ReflectiveCard,
  RotatingText,
  ScrambledText,
  ScrollFloat,
  ScrollReveal,
  ScrollRevealCSS,
  ScrollStack,
  ScrollStackItem,
  ScrollVelocity,
  ShapeBlur,
  ShinyText,
  Shuffle,
  SoftAurora,
  SplitText,
  TargetCursor,
  Terminal,
  TextPressure,
  TextType,
  TiltedCard,
  TrueFocus,
  VariableProximity,
  WorldMap,
};
