// Generates src/lib/live-scope.ts from the files in src/components/library/.
//
// The blog's <LiveStep> boxes are react-live, which evaluates JSX in the
// browser against a `scope` object. That scope used to be a hand-written list
// of ~63 imports in blog/[slug]/page.tsx, and forgetting an entry produced a
// blank demo box that still passed `next build`. This removes that failure mode
// by deriving the scope from the filesystem.
//
// Rules:
//   - every component file contributes its default export under the PascalCase
//     filename (ParallaxFloating.tsx -> ParallaxFloating, even though its
//     default is locally named `Floating`)
//   - files that also export an uppercase named component (FloatingElement,
//     ScrollStackItem) contribute that too, unless it duplicates the default
//
// Run via `pnpm generate:scope`. Also runs from `prebuild`, so a forgotten
// regeneration cannot ship.

import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const LIBRARY_DIR = join(ROOT, 'src/components/library');
const OUT_FILE = join(ROOT, 'src/lib/live-scope.ts');

const NAMED_EXPORT = /^export\s+(?:const|function)\s+([A-Z]\w*)/gm;

const entries = [];

for (const category of readdirSync(LIBRARY_DIR, { withFileTypes: true })
  .filter(d => d.isDirectory())
  .map(d => d.name)
  .sort()) {
  const files = readdirSync(join(LIBRARY_DIR, category))
    .filter(f => f.endsWith('.tsx'))
    .sort();

  for (const file of files) {
    const base = file.replace(/\.tsx$/, '');
    const source = readFileSync(join(LIBRARY_DIR, category, file), 'utf-8');

    if (!/export\s+default/.test(source)) {
      throw new Error(
        `${category}/${file} has no default export. Every library component needs one so the live scope can bind it.`
      );
    }

    const named = [...source.matchAll(NAMED_EXPORT)]
      .map(m => m[1])
      .filter(name => name !== base);

    entries.push({
      importPath: `@/components/library/${category}/${base}`,
      defaultName: base,
      named: [...new Set(named)],
    });
  }
}

const bindings = entries.flatMap(e => [e.defaultName, ...e.named]).sort();

const duplicates = bindings.filter((n, i) => bindings.indexOf(n) !== i);
if (duplicates.length > 0) {
  throw new Error(
    `Duplicate component names in the live scope: ${[...new Set(duplicates)].join(', ')}. Rename one of the files or its named export.`
  );
}

const imports = entries
  .map(e =>
    e.named.length > 0
      ? `import ${e.defaultName}, { ${e.named.join(', ')} } from '${e.importPath}';`
      : `import ${e.defaultName} from '${e.importPath}';`
  )
  .join('\n');

const output = `// GENERATED BY scripts/generate-scope.mjs -- DO NOT EDIT BY HAND.
// Run \`pnpm generate:scope\` after adding or renaming a library component.

${imports}

/** Every library component, keyed by the name a blog post writes in its LiveStep code. */
export const liveScope: Record<string, unknown> = {
${bindings.map(n => `  ${n},`).join('\n')}
};
`;

writeFileSync(OUT_FILE, output, 'utf-8');
console.log(
  `[generate-scope] wrote ${bindings.length} components to src/lib/live-scope.ts`
);
